allow-panic-in-tests = true
allow-unwrap-in-tests = true
allow-expect-in-tests = true
disallowed-methods = [
    "std::env::set_current_dir",
    "std::env::current_dir",
    "std::env::var",
    "std::env::var_os",
    "std::env::vars",
    "std::io::stdin",
    "tokio::io::stdin",
    "tokio::signal::ctrl_c",
    "std::process::exit",
    "std::process::Command::new",
    "tokio::process::Command::new",
    "tokio::spawn",
]
