.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-logout 1  "dalgon-logout " 
.SH NAME
dalgon\-logout \- Sign out from a provider.
.SH SYNOPSIS
\fBdalgon\-logout\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPROVIDER\fR] 
.SH DESCRIPTION
Sign out from a provider.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPROVIDER\fR]

