.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-dev-journal-diff 1  "dalgon-help-dev-journal-diff " 
.SH NAME
dalgon\-help\-dev\-journal\-diff \- Print the folded fields that differ between two journals.
.SH SYNOPSIS
\fBdalgon help dev journal diff\fR 
.SH DESCRIPTION
Print the folded fields that differ between two journals.
