.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-dev-journal-sidecar 1  "dalgon-help-dev-journal-sidecar " 
.SH NAME
dalgon\-help\-dev\-journal\-sidecar \- List or dump the sidecar files in a session directory.
.SH SYNOPSIS
\fBdalgon help dev journal sidecar\fR 
.SH DESCRIPTION
List or dump the sidecar files in a session directory.
