.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-dev-help-journal-diff 1  "dalgon-dev-help-journal-diff " 
.SH NAME
dalgon\-dev\-help\-journal\-diff \- Print the folded fields that differ between two journals.
.SH SYNOPSIS
\fBdalgon dev help journal diff\fR 
.SH DESCRIPTION
Print the folded fields that differ between two journals.
