.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-plugin-list 1  "dalgon-plugin-list " 
.SH NAME
dalgon\-plugin\-list \- List configured plugins and their persistent grants.
.SH SYNOPSIS
\fBdalgon\-plugin\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List configured plugins and their persistent grants.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
