.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-__sandbox 1  "dalgon-__sandbox " 
.SH NAME
dalgon\-__sandbox \- Enable the configured sandbox.
.SH SYNOPSIS
\fBdalgon __sandbox\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Enable the configured sandbox.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
