.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-dev-journal-torn 1  "dalgon-help-dev-journal-torn " 
.SH NAME
dalgon\-help\-dev\-journal\-torn \- Copy a journal with its tail cut mid\-record.
.SH SYNOPSIS
\fBdalgon help dev journal torn\fR 
.SH DESCRIPTION
Copy a journal with its tail cut mid\-record.
