.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-serve-help 1  "dalgon-serve-help " 
.SH NAME
dalgon\-serve\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgon serve help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
dalgon\-serve\-help\-token(1)
Create or replace the serve bearer token.
.TP
dalgon\-serve\-help\-help(1)
Print this message or the help of the given subcommand(s)
