.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-login 1  "dalgon-help-login " 
.SH NAME
dalgon\-help\-login \- Sign in to a provider or inspect sign\-in state.
.SH SYNOPSIS
\fBdalgon help login\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Sign in to a provider or inspect sign\-in state.
.SH SUBCOMMANDS
.TP
dalgon\-help\-login\-status(1)
Show provider sign\-in state.
