.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-dev-journal-help-help 1  "dalgon-dev-journal-help-help " 
.SH NAME
dalgon\-dev\-journal\-help\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgon dev journal help help\fR 
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
