.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-plugin-help-help 1  "dalgon-plugin-help-help " 
.SH NAME
dalgon\-plugin\-help\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgon plugin help help\fR 
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
