.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-dev-fold 1  "dalgon-dev-fold " 
.SH NAME
dalgon\-dev\-fold \- Print which folded fields each journal record changes.
.SH SYNOPSIS
\fBdalgon dev fold\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Print which folded fields each journal record changes.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
The journal file to explain
