.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-plugin-grant 1  "dalgon-help-plugin-grant " 
.SH NAME
dalgon\-help\-plugin\-grant \- Grant the configured capabilities declared by NAME.
.SH SYNOPSIS
\fBdalgon help plugin grant\fR 
.SH DESCRIPTION
Grant the configured capabilities declared by NAME.
