.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-rules 1  "dalgon-help-rules " 
.SH NAME
dalgon\-help\-rules \- Inspect or test stream rules.
.SH SYNOPSIS
\fBdalgon help rules\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Inspect or test stream rules.
.SH SUBCOMMANDS
.TP
dalgon\-help\-rules\-test(1)
Simulate a rule against one input.
