.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-help-serve 1  "dalgon-help-serve " 
.SH NAME
dalgon\-help\-serve \- Start the local control server or create its token.
.SH SYNOPSIS
\fBdalgon help serve\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Start the local control server or create its token.
.SH SUBCOMMANDS
.TP
dalgon\-help\-serve\-token(1)
Create or replace the serve bearer token.
