.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-plugin-help-grant 1  "dalgon-plugin-help-grant " 
.SH NAME
dalgon\-plugin\-help\-grant \- Grant the configured capabilities declared by NAME.
.SH SYNOPSIS
\fBdalgon plugin help grant\fR 
.SH DESCRIPTION
Grant the configured capabilities declared by NAME.
