.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-rules-help 1  "dalgon-rules-help " 
.SH NAME
dalgon\-rules\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgon rules help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
dalgon\-rules\-help\-test(1)
Simulate a rule against one input.
.TP
dalgon\-rules\-help\-help(1)
Print this message or the help of the given subcommand(s)
