.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-plugin-revoke 1  "dalgon-plugin-revoke " 
.SH NAME
dalgon\-plugin\-revoke \- Revoke every persistent grant for NAME.
.SH SYNOPSIS
\fBdalgon plugin revoke\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Revoke every persistent grant for NAME.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

