.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-dev-journal-help-sidecar 1  "dalgon-dev-journal-help-sidecar " 
.SH NAME
dalgon\-dev\-journal\-help\-sidecar \- List or dump the sidecar files in a session directory.
.SH SYNOPSIS
\fBdalgon dev journal help sidecar\fR 
.SH DESCRIPTION
List or dump the sidecar files in a session directory.
