.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-dev-journal-help-diff 1  "dalgon-dev-journal-help-diff " 
.SH NAME
dalgon\-dev\-journal\-help\-diff \- Print the folded fields that differ between two journals.
.SH SYNOPSIS
\fBdalgon dev journal help diff\fR 
.SH DESCRIPTION
Print the folded fields that differ between two journals.
