.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgon-dev-journal-replay 1  "dalgon-dev-journal-replay " 
.SH NAME
dalgon\-dev\-journal\-replay \- Fold a journal and print the recovered state.
.SH SYNOPSIS
\fBdalgon dev journal replay\fR [\fB\-h\fR|\fB\-\-help\fR] <\fIFILE\fR> 
.SH DESCRIPTION
Fold a journal and print the recovered state.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fIFILE\fR>
The journal file to fold
