//! Complete key table in context-ownership order.

use crossterm::event::{KeyCode, KeyModifiers};

use super::{Action, Binding, Key, Owner};

const NONE: KeyModifiers = KeyModifiers::NONE;
const CTRL: KeyModifiers = KeyModifiers::CONTROL;
const SHIFT: KeyModifiers = KeyModifiers::SHIFT;
const ALT: KeyModifiers = KeyModifiers::ALT;
const CTRL_SHIFT: KeyModifiers = KeyModifiers::CONTROL.union(KeyModifiers::SHIFT);
const fn key(code: KeyCode, modifiers: KeyModifiers) -> Key {
    Key::new(code, modifiers)
}

/// Complete key table in context-ownership order.
pub const BINDINGS: &[Binding] = &[
    Binding {
        owner: Owner::Dialog,
        action: Action::ApprovalAllowOnce,
        label: "Allow once",
        default: key(KeyCode::Char('y'), NONE),
        legacy: Some(key(KeyCode::Char('y'), NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::ApprovalAllowSession,
        label: "Allow for this session",
        default: key(KeyCode::Char('a'), NONE),
        legacy: Some(key(KeyCode::Char('a'), NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::ApprovalDeny,
        label: "Deny",
        default: key(KeyCode::Char('n'), NONE),
        legacy: Some(key(KeyCode::Esc, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::ApprovalView,
        label: "View full preview",
        default: key(KeyCode::Char('v'), NONE),
        legacy: Some(key(KeyCode::Char('v'), NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::AskMoveUp,
        label: "Move up",
        default: key(KeyCode::Up, NONE),
        legacy: Some(key(KeyCode::Up, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::AskMoveDown,
        label: "Move down",
        default: key(KeyCode::Down, NONE),
        legacy: Some(key(KeyCode::Down, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::AskToggle,
        label: "Toggle choice",
        default: key(KeyCode::Char(' '), NONE),
        legacy: Some(key(KeyCode::Char(' '), NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::AskSubmit,
        label: "Submit answer",
        default: key(KeyCode::Enter, NONE),
        legacy: Some(key(KeyCode::Enter, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::AskDismiss,
        label: "Dismiss question",
        default: key(KeyCode::Esc, NONE),
        legacy: Some(key(KeyCode::Esc, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::DialogFocusLeft,
        label: "Previous action",
        default: key(KeyCode::Left, NONE),
        legacy: Some(key(KeyCode::Left, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::DialogFocusRight,
        label: "Next action",
        default: key(KeyCode::Right, NONE),
        legacy: Some(key(KeyCode::Right, NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::DialogActivate,
        label: "Activate action",
        default: key(KeyCode::Enter, NONE),
        legacy: Some(key(KeyCode::Enter, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerMoveUp,
        label: "Move up",
        default: key(KeyCode::Up, NONE),
        legacy: Some(key(KeyCode::Char('k'), NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerMoveDown,
        label: "Move down",
        default: key(KeyCode::Down, NONE),
        legacy: Some(key(KeyCode::Char('j'), NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerPageUp,
        label: "Page up",
        default: key(KeyCode::PageUp, NONE),
        legacy: Some(key(KeyCode::PageUp, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerPageDown,
        label: "Page down",
        default: key(KeyCode::PageDown, NONE),
        legacy: Some(key(KeyCode::PageDown, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerFirst,
        label: "First row",
        default: key(KeyCode::Home, NONE),
        legacy: Some(key(KeyCode::Home, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerLast,
        label: "Last row",
        default: key(KeyCode::End, NONE),
        legacy: Some(key(KeyCode::End, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerAccept,
        label: "Choose",
        default: key(KeyCode::Enter, NONE),
        legacy: Some(key(KeyCode::Enter, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerCancel,
        label: "Cancel",
        default: key(KeyCode::Esc, NONE),
        legacy: Some(key(KeyCode::Esc, NONE)),
    },
    Binding {
        owner: Owner::Picker,
        action: Action::PickerDelete,
        label: "Delete row",
        default: key(KeyCode::Char('d'), NONE),
        legacy: Some(key(KeyCode::Char('d'), NONE)),
    },
    Binding {
        owner: Owner::App,
        action: Action::CloseOverlayOrInterrupt,
        label: "Close or interrupt",
        default: key(KeyCode::Esc, NONE),
        legacy: Some(key(KeyCode::Esc, NONE)),
    },
    Binding {
        owner: Owner::App,
        action: Action::CopySelection,
        label: "Copy selection",
        default: key(KeyCode::Char('c'), CTRL),
        legacy: Some(key(KeyCode::Char('c'), CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::Interrupt,
        label: "Interrupt turn",
        default: key(KeyCode::Char('c'), CTRL),
        legacy: Some(key(KeyCode::Char('c'), CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::QuitEmptyComposer,
        label: "Quit",
        default: key(KeyCode::Char('d'), CTRL),
        legacy: Some(key(KeyCode::Char('d'), CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::ExpandCollapse,
        label: "Expand or collapse",
        default: key(KeyCode::Char('o'), CTRL),
        legacy: Some(key(KeyCode::Char('o'), CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::TranscriptOverlay,
        label: "Transcript overlay",
        default: key(KeyCode::Char('t'), CTRL),
        legacy: None,
    },
    Binding {
        owner: Owner::App,
        action: Action::SearchTranscript,
        label: "Search transcript",
        default: key(KeyCode::Char('f'), CTRL_SHIFT),
        legacy: Some(key(KeyCode::F(3), NONE)),
    },
    Binding {
        owner: Owner::App,
        action: Action::PrevPrompt,
        label: "Previous prompt",
        default: key(KeyCode::Up, CTRL),
        legacy: Some(key(KeyCode::Up, CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::NextPrompt,
        label: "Next prompt",
        default: key(KeyCode::Down, CTRL),
        legacy: Some(key(KeyCode::Down, CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::ExternalEditor,
        label: "External editor",
        default: key(KeyCode::Char('g'), CTRL),
        legacy: Some(key(KeyCode::Char('g'), CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::Help,
        label: "Help",
        default: key(KeyCode::F(1), NONE),
        legacy: Some(key(KeyCode::F(1), NONE)),
    },
    Binding {
        owner: Owner::App,
        action: Action::ClearRegion,
        label: "Clear live region",
        default: key(KeyCode::Char('l'), CTRL),
        legacy: Some(key(KeyCode::Char('l'), CTRL)),
    },
    Binding {
        owner: Owner::App,
        action: Action::Suspend,
        label: "Suspend",
        default: key(KeyCode::Char('z'), CTRL),
        legacy: if cfg!(windows) {
            None
        } else {
            Some(key(KeyCode::Char('z'), CTRL))
        },
    },
    Binding {
        owner: Owner::App,
        action: Action::HistorySearch,
        label: "Search history",
        default: key(KeyCode::Char('r'), CTRL),
        legacy: Some(key(KeyCode::Char('r'), CTRL)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::RetryNow,
        label: "Retry now",
        default: key(KeyCode::Char('r'), NONE),
        legacy: Some(key(KeyCode::Char('r'), NONE)),
    },
    Binding {
        owner: Owner::Dialog,
        action: Action::RetryCancel,
        label: "Cancel retry",
        default: key(KeyCode::Char('c'), NONE),
        legacy: Some(key(KeyCode::Char('c'), NONE)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::Submit,
        label: "Send",
        default: key(KeyCode::Enter, NONE),
        legacy: Some(key(KeyCode::Enter, NONE)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::Newline,
        label: "Newline",
        default: key(KeyCode::Enter, SHIFT),
        legacy: Some(key(KeyCode::Char('j'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::AcceptCycleCompletion,
        label: "Complete",
        default: key(KeyCode::Tab, NONE),
        legacy: Some(key(KeyCode::Tab, NONE)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::HistoryPrev,
        label: "Previous history",
        default: key(KeyCode::Up, NONE),
        legacy: Some(key(KeyCode::Char('p'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::HistoryNext,
        label: "Next history",
        default: key(KeyCode::Down, NONE),
        legacy: Some(key(KeyCode::Char('n'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::CharLeft,
        label: "Move left",
        default: key(KeyCode::Left, NONE),
        legacy: Some(key(KeyCode::Char('b'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::CharRight,
        label: "Move right",
        default: key(KeyCode::Right, NONE),
        legacy: Some(key(KeyCode::Char('f'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::WordLeft,
        label: "Move word left",
        default: key(KeyCode::Left, ALT),
        legacy: Some(key(KeyCode::Char('b'), ALT)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::WordRight,
        label: "Move word right",
        default: key(KeyCode::Right, ALT),
        legacy: Some(key(KeyCode::Char('f'), ALT)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::LineStart,
        label: "Line start",
        default: key(KeyCode::Home, NONE),
        legacy: Some(key(KeyCode::Char('a'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::LineEnd,
        label: "Line end",
        default: key(KeyCode::End, NONE),
        legacy: Some(key(KeyCode::Char('e'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::DeleteWordBack,
        label: "Delete word back",
        default: key(KeyCode::Char('w'), CTRL),
        legacy: Some(key(KeyCode::Backspace, ALT)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::DeleteWordForward,
        label: "Delete word forward",
        default: key(KeyCode::Char('d'), ALT),
        legacy: Some(key(KeyCode::Char('d'), ALT)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::KillLineStart,
        label: "Delete to line start",
        default: key(KeyCode::Char('u'), CTRL),
        legacy: Some(key(KeyCode::Char('u'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::KillLineEnd,
        label: "Delete to line end",
        default: key(KeyCode::Char('k'), CTRL),
        legacy: Some(key(KeyCode::Char('k'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::Yank,
        label: "Yank",
        default: key(KeyCode::Char('y'), CTRL),
        legacy: Some(key(KeyCode::Char('y'), CTRL)),
    },
    Binding {
        owner: Owner::Composer,
        action: Action::Undo,
        label: "Undo",
        default: key(KeyCode::Char('_'), CTRL),
        legacy: Some(key(KeyCode::Char('_'), CTRL)),
    },
    Binding {
        owner: Owner::Editor,
        action: Action::CharLeft,
        label: "Move left",
        default: key(KeyCode::Left, NONE),
        legacy: Some(key(KeyCode::Char('b'), CTRL)),
    },
    Binding {
        owner: Owner::Editor,
        action: Action::CharRight,
        label: "Move right",
        default: key(KeyCode::Right, NONE),
        legacy: Some(key(KeyCode::Char('f'), CTRL)),
    },
    Binding {
        owner: Owner::Editor,
        action: Action::LineStart,
        label: "Line start",
        default: key(KeyCode::Home, NONE),
        legacy: Some(key(KeyCode::Char('a'), CTRL)),
    },
    Binding {
        owner: Owner::Editor,
        action: Action::LineEnd,
        label: "Line end",
        default: key(KeyCode::End, NONE),
        legacy: Some(key(KeyCode::Char('e'), CTRL)),
    },
    Binding {
        owner: Owner::Editor,
        action: Action::Undo,
        label: "Undo",
        default: key(KeyCode::Char('_'), CTRL),
        legacy: None,
    },
    Binding {
        owner: Owner::Editor,
        action: Action::ClearRegion,
        label: "Clear live region",
        default: key(KeyCode::Char('l'), CTRL),
        legacy: Some(key(KeyCode::Char('l'), CTRL)),
    },
    Binding {
        owner: Owner::Transcript,
        action: Action::TranscriptPageUp,
        label: "Transcript page up",
        default: key(KeyCode::PageUp, NONE),
        legacy: Some(key(KeyCode::Char('b'), CTRL)),
    },
    Binding {
        owner: Owner::Transcript,
        action: Action::TranscriptPageDown,
        label: "Transcript page down",
        default: key(KeyCode::PageDown, NONE),
        legacy: Some(key(KeyCode::Char('f'), CTRL)),
    },
    Binding {
        owner: Owner::Transcript,
        action: Action::TranscriptJumpLatest,
        label: "Jump to latest",
        default: key(KeyCode::End, NONE),
        legacy: Some(key(KeyCode::End, NONE)),
    },
];
