//! Per-language metric tables: token kinds counted toward complexity.

use crate::parse::Language;
pub(super) struct Table {
    pub functions: &'static [&'static str],
    pub decisions: &'static [&'static str],
    pub nesting: &'static [&'static str],
    pub folded: &'static [&'static str],
    pub flat: &'static [&'static str],
    pub else_parents: &'static [&'static str],
    pub bool_node: &'static str,
    pub bool_ops: &'static [&'static str],
    pub calls: &'static [&'static str],
    pub comments: &'static [&'static str],
    pub identifiers: &'static [&'static str],
    pub labeled_jumps: &'static [&'static str],
}

const RUST: Table = Table {
    functions: &["function_item"],
    decisions: &[
        "if_expression",
        "match_arm",
        "while_expression",
        "for_expression",
        "loop_expression",
        "try_expression",
    ],
    nesting: &[
        "if_expression",
        "match_expression",
        "while_expression",
        "for_expression",
        "loop_expression",
    ],
    folded: &["closure_expression"],
    flat: &["try_expression"],
    else_parents: &["else_clause"],
    bool_node: "binary_expression",
    bool_ops: &["&&", "||"],
    calls: &["call_expression"],
    comments: &["line_comment", "block_comment"],
    identifiers: &["identifier"],
    labeled_jumps: &["break_expression", "continue_expression"],
};

const OCAML: Table = Table {
    functions: &["let_binding"],
    decisions: &[
        "if_expression",
        "match_case",
        "while_expression",
        "for_expression",
        "when_expression",
    ],
    nesting: &[
        "if_expression",
        "match_expression",
        "while_expression",
        "for_expression",
        "try_expression",
    ],
    folded: &["fun_expression", "function_expression"],
    flat: &[],
    else_parents: &["else_clause"],
    bool_node: "infix_expression",
    bool_ops: &["&&", "||", "or"],
    calls: &["application_expression"],
    comments: &["comment"],
    identifiers: &["value_name"],
    labeled_jumps: &[],
};

const OCAML_INTERFACE: Table = Table {
    functions: &[],
    decisions: &[],
    nesting: &[],
    folded: &[],
    flat: &[],
    else_parents: &[],
    bool_node: "infix_expression",
    bool_ops: &["&&", "||", "or"],
    calls: &["application_expression"],
    comments: &["comment"],
    identifiers: &["value_name"],
    labeled_jumps: &[],
};

const TYPESCRIPT: Table = Table {
    functions: &[
        "function_declaration",
        "method_definition",
        "generator_function_declaration",
    ],
    decisions: &[
        "if_statement",
        "conditional_expression",
        "switch_case",
        "for_statement",
        "for_in_statement",
        "for_of_statement",
        "while_statement",
        "do_statement",
        "catch_clause",
    ],
    nesting: &[
        "if_statement",
        "switch_statement",
        "for_statement",
        "for_in_statement",
        "for_of_statement",
        "while_statement",
        "do_statement",
        "catch_clause",
        "conditional_expression",
    ],
    folded: &["arrow_function", "function_expression"],
    flat: &[],
    else_parents: &["else_clause"],
    bool_node: "binary_expression",
    bool_ops: &["&&", "||", "??"],
    calls: &["call_expression"],
    comments: &["comment"],
    identifiers: &["identifier"],
    labeled_jumps: &["break_statement", "continue_statement"],
};

const PYTHON: Table = Table {
    functions: &["function_definition"],
    decisions: &[
        "if_statement",
        "elif_clause",
        "while_statement",
        "for_statement",
        "except_clause",
        "conditional_expression",
        "for_in_clause",
        "if_clause",
        "case_clause",
    ],
    nesting: &[
        "if_statement",
        "while_statement",
        "for_statement",
        "except_clause",
        "match_statement",
        "conditional_expression",
    ],
    folded: &["lambda"],
    flat: &["elif_clause", "else_clause"],
    else_parents: &[],
    bool_node: "boolean_operator",
    bool_ops: &["and", "or"],
    calls: &["call"],
    comments: &["comment"],
    identifiers: &["identifier"],
    labeled_jumps: &[],
};

const GO: Table = Table {
    functions: &["function_declaration", "method_declaration"],
    decisions: &[
        "if_statement",
        "for_statement",
        "expression_case",
        "type_case",
        "communication_case",
    ],
    nesting: &[
        "if_statement",
        "for_statement",
        "expression_switch_statement",
        "type_switch_statement",
        "select_statement",
    ],
    folded: &["func_literal"],
    flat: &[],
    else_parents: &["if_statement"],
    bool_node: "binary_expression",
    bool_ops: &["&&", "||"],
    calls: &["call_expression"],
    comments: &["comment"],
    identifiers: &["identifier"],
    labeled_jumps: &["break_statement", "continue_statement", "goto_statement"],
};

const C: Table = Table {
    functions: &["function_definition"],
    decisions: &[
        "if_statement",
        "for_statement",
        "while_statement",
        "do_statement",
        "case_statement",
        "conditional_expression",
    ],
    nesting: &[
        "if_statement",
        "switch_statement",
        "for_statement",
        "while_statement",
        "do_statement",
        "conditional_expression",
    ],
    folded: &["lambda_expression"],
    flat: &["goto_statement"],
    else_parents: &["else_clause"],
    bool_node: "binary_expression",
    bool_ops: &["&&", "||"],
    calls: &["call_expression"],
    comments: &["comment"],
    identifiers: &["identifier"],
    labeled_jumps: &[],
};

const CPP: Table = Table {
    functions: &["function_definition"],
    decisions: &[
        "if_statement",
        "for_statement",
        "while_statement",
        "do_statement",
        "case_statement",
        "conditional_expression",
        "catch_clause",
    ],
    nesting: &[
        "if_statement",
        "switch_statement",
        "for_statement",
        "while_statement",
        "do_statement",
        "catch_clause",
        "conditional_expression",
    ],
    folded: &["lambda_expression"],
    flat: &["goto_statement"],
    else_parents: &["else_clause"],
    bool_node: "binary_expression",
    bool_ops: &["&&", "||"],
    calls: &["call_expression"],
    comments: &["comment"],
    identifiers: &["identifier"],
    labeled_jumps: &[],
};

pub(super) fn table(language: Language) -> &'static Table {
    match language {
        Language::Rust => &RUST,
        Language::Ocaml => &OCAML,
        Language::OcamlInterface => &OCAML_INTERFACE,
        Language::Python => &PYTHON,
        Language::JavaScript | Language::TypeScript | Language::Tsx => &TYPESCRIPT,
        Language::Go => &GO,
        Language::C => &C,
        Language::Cpp => &CPP,
    }
}
