//! Deterministic generator for embedded dal and Dalgona manuals.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt;
use std::fs;
use std::io::{self, Write};
use std::path::{Path, PathBuf};

/// Product namespace used in page URIs and generator diagnostics.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum Scheme {
    /// The dal manual (`dal://`).
    Dal,
    /// The Dalgona manual (`dalgona://`).
    Dalgona,
}

impl Scheme {
    pub(crate) fn uri(self) -> &'static str {
        match self {
            Self::Dal => "dal",
            Self::Dalgona => "dalgona",
        }
    }

    pub(crate) fn prefix(self) -> &'static str {
        match self {
            Self::Dal => "dal-docs",
            Self::Dalgona => "dalgona-docs",
        }
    }
}

/// Inputs for one deterministic manual generation.
#[derive(Clone, Debug)]
pub struct GenArgs {
    /// Manual tree holding `pages` and Markdown files.
    pub dir: PathBuf,
    /// Optional port tree; each child becomes an `examples/` page.
    pub examples: Option<PathBuf>,
    /// Roots scanned for source ownership and page links.
    pub scan: Vec<PathBuf>,
    /// URI scheme used by the generated pages.
    pub scheme: Scheme,
}

/// One generator error with a stable ordering key and rendered diagnostic.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct GenError {
    path: PathBuf,
    line: usize,
    message: String,
}

impl GenError {
    pub(crate) fn new(path: impl Into<PathBuf>, line: usize, message: String) -> Self {
        Self {
            path: path.into(),
            line,
            message,
        }
    }
}

impl fmt::Display for GenError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        formatter.write_str(&self.message)
    }
}

impl std::error::Error for GenError {}

#[derive(Clone, Debug)]
struct PageSpec {
    name: String,
    owner: String,
    max_lines: usize,
    line: usize,
}

/// Generates the complete Rust module for one manual.
///
/// Reads without following symlinks, normalizes CRLF, checks budgets, and
/// emits pages in byte order.
///
/// # Errors
/// Returns all errors in stable file and line order.
pub fn generate(args: &GenArgs) -> Result<String, Vec<GenError>> {
    let mut errors = Vec::new();
    let prefix = args.scheme.prefix();
    let list_path = args.dir.join("pages");
    let specs = read_specs(args, &mut errors);
    let listed: BTreeMap<_, _> = specs
        .iter()
        .map(|spec| (spec.name.as_str(), spec))
        .collect();
    let mut pages = read_manual(args, &mut errors);
    let manual_pages: BTreeSet<_> = pages.keys().cloned().collect();
    if let Some(examples) = &args.examples {
        pages.extend(assemble_examples(args, examples, &listed, &mut errors));
    }
    check_specs(args, &specs, &pages, &mut errors);
    for name in &manual_pages {
        if !listed.contains_key(name.as_str()) {
            let path = args.dir.join(format!("{name}.md"));
            errors.push(GenError::new(
                &path,
                0,
                format!(
                    "{prefix}: {} is not listed in {}. Add a line \"{name} <readers> <owner> <max-lines>\", or delete the file.",
                    path.display(),
                    list_path.display()
                ),
            ));
        }
    }
    for (name, text) in &pages {
        if let Some(spec) = listed.get(name.as_str()) {
            check_page(args, spec, text, &mut errors);
        }
    }
    check_links(args, &pages, &mut errors);
    let total: usize = pages.values().map(String::len).sum();
    if total > 1_048_576 {
        errors.push(GenError::new(
            &args.dir,
            0,
            format!(
                "{prefix}: the {}:// pages hold {total} bytes; the limit is 1048576.",
                args.scheme.uri()
            ),
        ));
    }
    if !errors.is_empty() {
        errors.sort_by(|a, b| {
            a.path
                .cmp(&b.path)
                .then(a.line.cmp(&b.line))
                .then(a.message.cmp(&b.message))
        });
        return Err(errors);
    }
    let mut out = String::from(
        "// @generated by docs-gen. Do not edit.\npub(crate) static PAGES: &[(&str, &str)] = &[\n",
    );
    for (name, text) in pages {
        out.push_str("    (");
        let _ = std::fmt::Write::write_fmt(&mut out, format_args!("{name:?}, {text:?}"));
        out.push_str("),\n");
    }
    out.push_str("];\n");
    Ok(out)
}

fn parse_spec_line(
    args: &GenArgs,
    path: &Path,
    fields: &[&str],
    no: usize,
    seen: &mut BTreeSet<String>,
    specs: &mut Vec<PageSpec>,
    errors: &mut Vec<GenError>,
) {
    let prefix = args.scheme.prefix();
    let f = fields;
    if f.len() != 4 {
        errors.push(GenError::new(
            path,
            no,
            format!(
                "{prefix}: {}:{no}: expected \"<page> <readers> <owner> <max-lines>\".",
                path.display()
            ),
        ));
        return;
    }
    if !page_valid(f[0]) {
        errors.push(GenError::new(
            path,
            no,
            format!(
                "{prefix}: {}:{no}: \"{}\" is not a page name. Use lowercase letters, digits, and hyphens, with / between parts.",
                path.display(),
                f[0]
            ),
        ));
        return;
    }
    if !seen.insert(f[0].to_owned()) {
        errors.push(GenError::new(
            path,
            no,
            format!(
                "{prefix}: {}:{no}: {}://{} is listed twice.",
                path.display(),
                args.scheme.uri(),
                f[0]
            ),
        ));
        return;
    }
    check_spec_readers(path, prefix, f[1], no, errors);
    if !owner_token_valid(f[2]) {
        errors.push(GenError::new(
            path,
            no,
            format!(
                "{prefix}: {}:{no}: owner \"{}\" is not a valid owner name.",
                path.display(),
                f[2]
            ),
        ));
    }
    match f[3].parse::<usize>() {
        Ok(n) if (1..=1500).contains(&n) => specs.push(PageSpec {
            name: f[0].to_owned(),
            owner: f[2].to_owned(),
            max_lines: n,
            line: no,
        }),
        _ => errors.push(GenError::new(
            path,
            no,
            format!(
                "{prefix}: {}:{no}: max-lines must be from 1 to 1500.",
                path.display()
            ),
        )),
    }
}

fn check_spec_readers(
    path: &Path,
    prefix: &str,
    readers: &str,
    no: usize,
    errors: &mut Vec<GenError>,
) {
    for reader in readers.split(',') {
        if !matches!(
            reader,
            "user" | "model" | "author" | "integrator" | "maintainer"
        ) {
            errors.push(GenError::new(
                path,
                no,
                format!(
                    "{prefix}: {}:{no}: unknown reader \"{reader}\". Use user, model, author, integrator, or maintainer.",
                    path.display()
                ),
            ));
        }
    }
}

fn read_specs(args: &GenArgs, errors: &mut Vec<GenError>) -> Vec<PageSpec> {
    let path = args.dir.join("pages");
    let prefix = args.scheme.prefix();
    let Some(text) = read_text(&path, prefix, errors) else {
        return Vec::new();
    };
    let mut specs = Vec::new();
    let mut seen = BTreeSet::new();
    let mut has_line = false;
    for (index, line) in text.lines().enumerate() {
        let fields: Vec<_> = line.split_whitespace().collect();
        if fields.is_empty() {
            continue;
        }
        has_line = true;
        parse_spec_line(
            args,
            &path,
            &fields,
            index + 1,
            &mut seen,
            &mut specs,
            errors,
        );
    }
    if !has_line {
        errors.push(GenError::new(
            &path,
            0,
            format!("{prefix}: {}: the page list is empty.", path.display()),
        ));
    }
    specs
}

fn assemble_port(
    args: &GenArgs,
    root: &Path,
    entry: &str,
    listed: &BTreeMap<&str, &PageSpec>,
    errors: &mut Vec<GenError>,
) -> Option<(String, String)> {
    let prefix = args.scheme.prefix();
    let dir = root.join(entry);
    let meta = read_metadata(&dir, prefix, errors)?;
    if !meta.is_dir() {
        errors.push(GenError::new(
            &dir,
            0,
            format!(
                "{prefix}: {}: only plugin directories may live here.",
                dir.display()
            ),
        ));
        return None;
    }
    if entry.contains('/') || !page_valid(entry) {
        errors.push(GenError::new(
            &dir,
            0,
            format!(
                "{prefix}: {}: the file name is not a page name. Use lowercase letters, digits, and hyphens.",
                dir.display()
            ),
        ));
        return None;
    }
    let readme = dir.join("README.md");
    let plugin = dir.join("plugin.star");
    let has_readme = read_metadata(&readme, prefix, errors).is_some_and(|m| m.is_file());
    let has_plugin = read_metadata(&plugin, prefix, errors).is_some_and(|m| m.is_file());
    if !has_readme {
        errors.push(GenError::new(
            &dir,
            0,
            format!("{prefix}: {}: README.md is missing.", dir.display()),
        ));
    }
    if !has_plugin {
        errors.push(GenError::new(
            &dir,
            0,
            format!("{prefix}: {}: plugin.star is missing.", dir.display()),
        ));
    }
    if !(has_readme && has_plugin) {
        return None;
    }
    let readme_text = read_text(&readme, prefix, errors)?;
    let mut files = Vec::new();
    collect_port_files(&dir, &mut files, prefix, errors);
    files.retain(|path| path != &readme);
    files.sort_by_key(|path| relative_name(&dir, path));
    let mut text = readme_text;
    text.push_str("\n## Files\n");
    for file in files {
        let Some(content) = read_text(&file, prefix, errors) else {
            continue;
        };
        let fence = "`".repeat(longest_backticks(&content).saturating_add(1).max(3));
        text.push_str("\n### ");
        text.push_str(&relative_name(&dir, &file));
        text.push_str("\n\n");
        text.push_str(&fence);
        text.push_str(language_tag(&file));
        text.push('\n');
        text.push_str(&content);
        if !text.ends_with('\n') {
            text.push('\n');
        }
        text.push_str(&fence);
        text.push('\n');
    }
    let name = format!("examples/{entry}");
    if !listed.contains_key(name.as_str()) {
        let path = args.dir.join(format!("{name}.md"));
        errors.push(GenError::new(
            &path,
            0,
            format!(
                "{prefix}: {} is not listed in {}. Add a line \"{name} <readers> <owner> <max-lines>\", or delete the file.",
                path.display(),
                args.dir.join("pages").display()
            ),
        ));
    }
    Some((name, text))
}

fn owner_token_valid(owner: &str) -> bool {
    let mut bytes = owner.bytes();
    matches!(bytes.next(), Some(b'a'..=b'z'))
        && bytes.all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'-')
}

fn owner_exists(owner: &str, scheme: Scheme, manual_dir: &Path, scan: &[PathBuf]) -> bool {
    let under = |sub: &str| scan.iter().any(|root| root.join(sub).is_dir());
    let dal = || {
        SCAN_DAL
            .iter()
            .any(|(token, sub)| *token == owner && under(sub))
            || (owner == "docs"
                && scan
                    .iter()
                    .any(|root| root == manual_dir || root.join("docs") == *manual_dir))
    };
    let dalgona = || {
        SCAN_DALGONA
            .iter()
            .any(|(token, sub)| *token == owner && under(sub))
            || (owner == "docs"
                && scan
                    .iter()
                    .any(|root| root == manual_dir || root.join("docs") == *manual_dir))
    };
    match scheme {
        Scheme::Dal => dal(),
        Scheme::Dalgona => dalgona(),
    }
}

const SCAN_DAL: &[(&str, &str)] = &[
    ("cli-entry", "crates/dalgon/src"),
    ("platform-paths", "crates/dalgon/src"),
    ("sandbox", "crates/dalgon/src"),
    ("product", "crates/dalgon/src"),
    ("slash-registry", "crates/dal-ext/src"),
    ("prompt-builder", "crates/dal-ext/src"),
    ("rules-extension", "crates/dal-ext/src"),
    ("config-loader", "crates/dal-core/src"),
    ("model-catalog", "crates/dal-core/src"),
    ("journal", "crates/dal-core/src"),
    ("plugin-system", "crates/dal-star/src"),
    ("guard-extension", "crates/dal-tools/src"),
    ("wire-adapters", "crates/dal-wire/src"),
    ("wire-codecs", "crates/dal-wire/src"),
    ("router-a2a", "crates/dal-wire/src"),
    ("host-agent-seam", "crates/dal-agent/src"),
    ("tool-registry", "crates/dal-agent/src"),
    ("tui-keymap", "crates/dal-tui/src"),
];

const SCAN_DALGONA: &[(&str, &str)] = &[
    ("config-loader", "crates/dal-core/src"),
    ("product", "crates/dalgona/src"),
    ("batteries", "crates/dalgona-batteries/src"),
    ("orchestration", "crates/dalgona-batteries/src"),
    ("history", "crates/dalgona-batteries/src"),
    ("quality", "crates/dalgona-batteries/src"),
    ("judged", "crates/dalgona-batteries/src"),
    ("web", "crates/dalgona-batteries/src"),
    ("work", "crates/dalgona-batteries/src"),
    ("mcp", "crates/dalgona-batteries/src"),
    ("review", "crates/dalgona-batteries/src"),
];

fn check_specs(
    args: &GenArgs,
    specs: &[PageSpec],
    pages: &BTreeMap<String, String>,
    errors: &mut Vec<GenError>,
) {
    let prefix = args.scheme.prefix();
    let list_path = args.dir.join("pages");
    for spec in specs {
        if !owner_exists(&spec.owner, args.scheme, &args.dir, &args.scan) {
            errors.push(GenError::new(
                &list_path,
                spec.line,
                format!(
                    "{prefix}: {}:{}: owner {} has no source under the scanned directories.",
                    list_path.display(),
                    spec.line,
                    spec.owner
                ),
            ));
        }
        if pages.contains_key(&spec.name) {
            continue;
        }
        if let Some(example) = spec.name.strip_prefix("examples/") {
            let root = args.examples.as_deref().unwrap_or(Path::new("examples"));
            errors.push(GenError::new(
                &list_path,
                spec.line,
                format!(
                    "{prefix}: {} lists {}://{}, but {}/{} does not exist.",
                    list_path.display(),
                    args.scheme.uri(),
                    spec.name,
                    root.display(),
                    example
                ),
            ));
        } else {
            let path = args.dir.join(format!("{}.md", spec.name));
            errors.push(GenError::new(
                &path,
                0,
                format!(
                    "{prefix}: {} lists {}://{}, but {} does not exist.",
                    list_path.display(),
                    args.scheme.uri(),
                    spec.name,
                    path.display()
                ),
            ));
        }
    }
}

fn read_manual(args: &GenArgs, errors: &mut Vec<GenError>) -> BTreeMap<String, String> {
    let mut pages = BTreeMap::new();
    let prefix = args.scheme.prefix();
    let entries = match read_sorted(&args.dir) {
        Ok(entries) => entries,
        Err(error) => {
            errors.push(GenError::new(
                &args.dir,
                0,
                format!("{prefix}: {}: {error}", args.dir.display()),
            ));
            return pages;
        }
    };
    for entry in entries {
        let path = args.dir.join(&entry);
        if entry == "pages" {
            continue;
        }
        if !entry.to_ascii_lowercase().ends_with(".md") {
            errors.push(GenError::new(
                &path,
                0,
                format!(
                    "{prefix}: {}: only .md files and the pages list may live here.",
                    path.display()
                ),
            ));
            continue;
        }
        let name = entry.trim_end_matches(".md");
        if name.contains('/') || !page_valid(name) {
            errors.push(GenError::new(
                 &path,
                 0,
                 format!(
                     "{prefix}: {}: the file name is not a page name. Use lowercase letters, digits, and hyphens.",
                     path.display()
                 ),
             ));
            continue;
        }
        if let Some(text) = read_text(&path, prefix, errors) {
            pages.insert(name.to_owned(), text);
        }
    }
    pages
}

fn assemble_examples(
    args: &GenArgs,
    root: &Path,
    listed: &BTreeMap<&str, &PageSpec>,
    errors: &mut Vec<GenError>,
) -> BTreeMap<String, String> {
    let prefix = args.scheme.prefix();
    let mut pages = BTreeMap::new();
    let entries = match read_sorted(root) {
        Ok(entries) => entries,
        Err(error) => {
            errors.push(GenError::new(
                root,
                0,
                format!("{prefix}: {}: {error}", root.display()),
            ));
            return pages;
        }
    };
    for entry in entries {
        if let Some((name, text)) = assemble_port(args, root, &entry, listed, errors) {
            pages.insert(name, text);
        }
    }
    pages
}

fn collect_port_files(
    current: &Path,
    files: &mut Vec<PathBuf>,
    prefix: &str,
    errors: &mut Vec<GenError>,
) {
    let entries = match read_sorted(current) {
        Ok(entries) => entries,
        Err(error) => {
            errors.push(GenError::new(
                current,
                0,
                format!("{prefix}: {}: {error}", current.display()),
            ));
            return;
        }
    };
    for entry in entries {
        let path = current.join(entry);
        let Some(meta) = read_metadata(&path, prefix, errors) else {
            continue;
        };
        if meta.is_dir() {
            collect_port_files(&path, files, prefix, errors);
        } else if meta.is_file() {
            files.push(path);
        }
    }
}

fn read_metadata(path: &Path, prefix: &str, errors: &mut Vec<GenError>) -> Option<fs::Metadata> {
    match fs::symlink_metadata(path) {
        Ok(meta) if meta.file_type().is_symlink() => {
            errors.push(GenError::new(
                path,
                0,
                format!(
                    "{prefix}: {}: symbolic links are not allowed.",
                    path.display()
                ),
            ));
            None
        }
        Ok(meta) => Some(meta),
        Err(error) => {
            errors.push(GenError::new(
                path,
                0,
                format!("{prefix}: {}: {error}", path.display()),
            ));
            None
        }
    }
}

fn read_sorted(path: &Path) -> io::Result<Vec<String>> {
    let mut entries = fs::read_dir(path)?
        .map(|entry| entry.map(|entry| entry.file_name()))
        .collect::<Result<Vec<_>, _>>()?;
    entries.sort_by(|a, b| a.as_encoded_bytes().cmp(b.as_encoded_bytes()));
    Ok(entries
        .into_iter()
        .map(|entry| entry.to_string_lossy().into_owned())
        .collect())
}

fn read_text(path: &Path, prefix: &str, errors: &mut Vec<GenError>) -> Option<String> {
    let meta = read_metadata(path, prefix, errors)?;
    if !meta.is_file() {
        errors.push(GenError::new(
            path,
            0,
            format!("{prefix}: {}: expected a regular file.", path.display()),
        ));
        return None;
    }
    match fs::read(path) {
        Ok(bytes) => match std::str::from_utf8(&bytes) {
            Ok(text) => Some(text.replace("\r\n", "\n")),
            Err(error) => {
                errors.push(GenError::new(
                    path,
                    0,
                    format!(
                        "{prefix}: {}: not valid UTF-8 at byte {}.",
                        path.display(),
                        error.valid_up_to()
                    ),
                ));
                None
            }
        },
        Err(error) => {
            errors.push(GenError::new(
                path,
                0,
                format!("{prefix}: {}: {error}", path.display()),
            ));
            None
        }
    }
}

fn relative_name(root: &Path, path: &Path) -> String {
    path.strip_prefix(root)
        .unwrap_or(path)
        .components()
        .map(|part| part.as_os_str().to_string_lossy())
        .collect::<Vec<_>>()
        .join("/")
}

fn language_tag(path: &Path) -> &'static str {
    let tag = path.extension().and_then(|extension| extension.to_str());
    if tag.is_some_and(|tag| tag.eq_ignore_ascii_case("star")) {
        "starlark"
    } else if tag.is_some_and(|tag| tag.eq_ignore_ascii_case("md")) {
        "markdown"
    } else if tag.is_some_and(|tag| tag.eq_ignore_ascii_case("toml")) {
        "toml"
    } else if tag.is_some_and(|tag| tag.eq_ignore_ascii_case("rs")) {
        "rust"
    } else {
        ""
    }
}

fn longest_backticks(text: &str) -> usize {
    text.as_bytes()
        .split(|byte| *byte != b'`')
        .map(<[u8]>::len)
        .max()
        .unwrap_or(0)
}

fn page_path(args: &GenArgs, page: &str) -> PathBuf {
    if let Some(name) = page.strip_prefix("examples/") {
        args.examples
            .as_deref()
            .unwrap_or(Path::new("examples"))
            .join(name)
    } else {
        args.dir.join(format!("{page}.md"))
    }
}

fn check_page(args: &GenArgs, spec: &PageSpec, text: &str, errors: &mut Vec<GenError>) {
    let path = page_path(args, &spec.name);
    let prefix = args.scheme.prefix();
    let lines = text.lines().count();
    if text.len() > 49_152 {
        errors.push(GenError::new(
            &path,
            0,
            format!(
                "{prefix}: {}: {} bytes; the limit is 49152. Split the page.",
                path.display(),
                text.len()
            ),
        ));
    }
    if lines > 1500 {
        errors.push(GenError::new(
            &path,
            0,
            format!(
                "{prefix}: {}: {lines} lines; the limit is 1500. Split the page.",
                path.display()
            ),
        ));
    }
    if lines > spec.max_lines {
        errors.push(GenError::new(
            &path,
            0,
            format!(
                "{prefix}: {}: {lines} lines; {} allows {}.",
                path.display(),
                args.dir.join("pages").display(),
                spec.max_lines
            ),
        ));
    }
    let title = text.lines().next().unwrap_or_default().strip_prefix("# ");
    if !title.is_some_and(|title| !title.is_empty() && title.len() <= 80) {
        errors.push(GenError::new(
            &path,
            1,
            format!(
                "{prefix}: {}:1: the first line must be \"# \" and a title of 1 to 80 bytes.",
                path.display()
            ),
        ));
    }
}

fn check_links(args: &GenArgs, pages: &BTreeMap<String, String>, errors: &mut Vec<GenError>) {
    let prefix = args.scheme.prefix();
    let scheme = args.scheme.uri();
    let mut files = BTreeSet::<PathBuf>::new();
    for root in &args.scan {
        collect_scan_files(root, &mut files);
    }
    for page in pages.keys() {
        if !page.starts_with("examples/") {
            files.insert(args.dir.join(format!("{page}.md")));
        }
    }
    for path in files {
        let Some(text) = read_text(&path, prefix, errors) else {
            continue;
        };
        for (index, line) in text.lines().enumerate() {
            for page in own_scheme_links(line, scheme) {
                if page.is_empty() || page == "index" || page.ends_with('/') {
                    continue;
                }
                if !page_valid(&page) || !pages.contains_key(&page) {
                    errors.push(GenError::new(
                        &path,
                        index + 1,
                        format!(
                            "{prefix}: {}:{}: {scheme}://{page} is not a page.",
                            path.display(),
                            index + 1
                        ),
                    ));
                }
            }
        }
    }
}

fn collect_scan_files(current: &Path, files: &mut BTreeSet<PathBuf>) {
    let Ok(entries) = read_sorted(current) else {
        return;
    };
    for entry in entries {
        let path = current.join(entry);
        let Ok(meta) = fs::symlink_metadata(&path) else {
            continue;
        };
        if meta.file_type().is_symlink() {
            continue;
        }
        if meta.is_dir() {
            let Some(name) = path.file_name().and_then(|name| name.to_str()) else {
                continue;
            };
            if name == "target" || name.starts_with('.') {
                continue;
            }
            collect_scan_files(&path, files);
        } else if meta.is_file() && scannable(&path) {
            files.insert(path);
        }
    }
}

fn scannable(path: &Path) -> bool {
    path.extension()
        .and_then(|extension| extension.to_str())
        .is_some_and(|extension| {
            extension.eq_ignore_ascii_case("rs")
                || extension.eq_ignore_ascii_case("md")
                || extension.eq_ignore_ascii_case("star")
        })
}

fn own_scheme_links(line: &str, scheme: &str) -> Vec<String> {
    let bytes = line.as_bytes();
    let marker = b"://";
    let scheme_bytes = scheme.as_bytes();
    let mut found = Vec::new();
    let mut cursor = 0;
    while cursor + marker.len() <= bytes.len() {
        let Some(relative) = line[cursor..].find("://") else {
            break;
        };
        let separator = cursor + relative;
        let start = separator.saturating_sub(scheme_bytes.len());
        let before = start
            .checked_sub(1)
            .and_then(|index| bytes.get(index))
            .copied();
        if start + scheme_bytes.len() <= separator
            && &bytes[start..separator] == scheme_bytes
            && !before.is_some_and(|byte| byte.is_ascii_alphanumeric() || byte == b'_')
        {
            let page_start = separator + marker.len();
            let mut end = page_start;
            while end < bytes.len()
                && !bytes[end].is_ascii_whitespace()
                && !matches!(
                    bytes[end],
                    b'`' | b'<'
                        | b'>'
                        | b'"'
                        | b'\''
                        | b'('
                        | b')'
                        | b'['
                        | b']'
                        | b'{'
                        | b'}'
                        | b'|'
                )
            {
                end += 1;
            }
            let mut page = String::from_utf8_lossy(&bytes[page_start..end]).into_owned();
            while matches!(
                page.as_bytes().last(),
                Some(b'.' | b',' | b';' | b'!' | b'?' | b':')
            ) {
                page.pop();
            }
            found.push(page);
        }
        cursor = separator + marker.len();
    }
    found
}

/// Returns whether `page` matches the lowercase, slash-separated page grammar.
#[must_use]
pub fn page_valid(page: &str) -> bool {
    if page.is_empty() {
        return false;
    }
    page.split('/').all(|segment| {
        let mut bytes = segment.bytes();
        matches!(bytes.next(), Some(b'a'..=b'z' | b'0'..=b'9'))
            && bytes.all(|byte| byte.is_ascii_lowercase() || byte.is_ascii_digit() || byte == b'-')
    })
}

/// Runs the command-line interface used by the `docs-gen` binary.
///
/// # Errors
/// Returns 0 on success, 1 for manual validation errors, and 2 for invalid
/// arguments or output failures.
#[must_use]
pub fn cli<I: Iterator<Item = String>>(mut args: I) -> i32 {
    let _program = args.next();
    let mut scheme = None;
    let mut dir = None;
    let mut examples = None;
    let mut scan = Vec::new();
    let mut out = None;
    let mut argument_error = None;
    while let Some(flag) = args.next() {
        let Some(value) = args.next() else {
            argument_error = Some(format!("missing value for {flag}"));
            break;
        };
        match flag.as_str() {
            "--scheme" => scheme = Some(value),
            "--dir" => dir = Some(PathBuf::from(value)),
            "--examples" => examples = Some(PathBuf::from(value)),
            "--scan" => scan.push(PathBuf::from(value)),
            "--out" => out = Some(PathBuf::from(value)),
            _ => {
                argument_error = Some(format!("unknown argument {flag}"));
                break;
            }
        }
    }
    let parsed = match scheme.as_deref() {
        Some("dal") => Some(Scheme::Dal),
        Some("dalgona") => Some(Scheme::Dalgona),
        Some(value) => {
            argument_error = Some(format!("unknown scheme {value}"));
            None
        }
        None => {
            argument_error = Some("missing --scheme".to_owned());
            None
        }
    };
    let Some(scheme) = parsed else {
        return cli_error(
            "dal-docs",
            &argument_error.unwrap_or_else(|| "invalid arguments".to_owned()),
        );
    };
    let (Some(dir), Some(out)) = (dir, out) else {
        return cli_error(scheme.prefix(), "missing --dir or --out");
    };
    if let Some(error) = argument_error {
        return cli_error(scheme.prefix(), &error);
    }
    match generate(&GenArgs {
        dir,
        examples,
        scan,
        scheme,
    }) {
        Ok(module) => match fs::write(out, module) {
            Ok(()) => 0,
            Err(error) => cli_error(scheme.prefix(), &format!("cannot write output: {error}")),
        },
        Err(errors) => {
            let mut stderr = io::stderr().lock();
            for error in errors {
                let _ = writeln!(stderr, "{error}");
            }
            1
        }
    }
}

fn cli_error(prefix: &str, message: &str) -> i32 {
    let _ = writeln!(io::stderr().lock(), "{prefix}: {message}");
    2
}
