.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-acp 1  "dalgona-acp " 
.SH NAME
dalgona\-acp \- Serve the Agent Client Protocol on standard input and output.
.SH SYNOPSIS
\fBdalgona acp\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Serve the Agent Client Protocol on standard input and output.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
