.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-help-serve 1  "dalgona-help-serve " 
.SH NAME
dalgona\-help\-serve \- Start the local control server or create its token.
.SH SYNOPSIS
\fBdalgona help serve\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Start the local control server or create its token.
.SH SUBCOMMANDS
.TP
dalgona\-help\-serve\-token(1)
Create or replace the serve bearer token.
