.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-rules-help 1  "dalgona-rules-help " 
.SH NAME
dalgona\-rules\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgona rules help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
dalgona\-rules\-help\-test(1)
Simulate a rule against one input.
.TP
dalgona\-rules\-help\-help(1)
Print this message or the help of the given subcommand(s)
