.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-help-login 1  "dalgona-help-login " 
.SH NAME
dalgona\-help\-login \- Sign in to a provider or inspect sign\-in state.
.SH SYNOPSIS
\fBdalgona help login\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Sign in to a provider or inspect sign\-in state.
.SH SUBCOMMANDS
.TP
dalgona\-help\-login\-status(1)
Show provider sign\-in state.
