.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-plugin-help-list 1  "dalgona-plugin-help-list " 
.SH NAME
dalgona\-plugin\-help\-list \- List configured plugins and their persistent grants.
.SH SYNOPSIS
\fBdalgona plugin help list\fR 
.SH DESCRIPTION
List configured plugins and their persistent grants.
