.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-plugin-help-grant 1  "dalgona-plugin-help-grant " 
.SH NAME
dalgona\-plugin\-help\-grant \- Grant the configured capabilities declared by NAME.
.SH SYNOPSIS
\fBdalgona plugin help grant\fR 
.SH DESCRIPTION
Grant the configured capabilities declared by NAME.
