.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-serve-help 1  "dalgona-serve-help " 
.SH NAME
dalgona\-serve\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgona serve help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
dalgona\-serve\-help\-token(1)
Create or replace the serve bearer token.
.TP
dalgona\-serve\-help\-help(1)
Print this message or the help of the given subcommand(s)
