.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-help-plugin-grant 1  "dalgona-help-plugin-grant " 
.SH NAME
dalgona\-help\-plugin\-grant \- Grant the configured capabilities declared by NAME.
.SH SYNOPSIS
\fBdalgona help plugin grant\fR 
.SH DESCRIPTION
Grant the configured capabilities declared by NAME.
