.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-models 1  "dalgona-models " 
.SH NAME
dalgona\-models \- List models and show built\-in prices, price source, and fetch date when available.
.SH SYNOPSIS
\fBdalgona models\fR [\fB\-\-json\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIPATTERN\fR] 
.SH DESCRIPTION
List models and show built\-in prices, price source, and fetch date when available.
.SH OPTIONS
.TP
\fB\-\-json\fR
Print model data as JSON.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPATTERN\fR]
Filter the model list by PATTERN.
