.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-help-plugin-list 1  "dalgona-help-plugin-list " 
.SH NAME
dalgona\-help\-plugin\-list \- List configured plugins and their persistent grants.
.SH SYNOPSIS
\fBdalgona help plugin list\fR 
.SH DESCRIPTION
List configured plugins and their persistent grants.
