.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-docs 1  "dalgona-docs " 
.SH NAME
dalgona\-docs \- Read a dalgon documentation page.
.SH SYNOPSIS
\fBdalgona docs\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIURI\fR] 
.SH DESCRIPTION
Read a dalgon documentation page.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIURI\fR]

