.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-plugin-list 1  "dalgona-plugin-list " 
.SH NAME
dalgona\-plugin\-list \- List configured plugins and their persistent grants.
.SH SYNOPSIS
\fBdalgona\-plugin\-list\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
List configured plugins and their persistent grants.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
