.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-serve-token 1  "dalgona-serve-token " 
.SH NAME
dalgona\-serve\-token \- Create or replace the serve bearer token.
.SH SYNOPSIS
\fBdalgona\-serve\-token\fR [\fB\-\-force\fR] [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Create or replace the serve bearer token.
.SH OPTIONS
.TP
\fB\-\-force\fR
Replace an existing token after writing the new token atomically.
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
