.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-login-help 1  "dalgona-login-help " 
.SH NAME
dalgona\-login\-help \- Print this message or the help of the given subcommand(s)
.SH SYNOPSIS
\fBdalgona login help\fR [\fIsubcommands\fR]
.SH DESCRIPTION
Print this message or the help of the given subcommand(s)
.SH SUBCOMMANDS
.TP
dalgona\-login\-help\-status(1)
Show provider sign\-in state.
.TP
dalgona\-login\-help\-help(1)
Print this message or the help of the given subcommand(s)
