.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-plugin-revoke 1  "dalgona-plugin-revoke " 
.SH NAME
dalgona\-plugin\-revoke \- Revoke every persistent grant for NAME.
.SH SYNOPSIS
\fBdalgona\-plugin\-revoke\fR [\fB\-h\fR|\fB\-\-help\fR] <\fINAME\fR> 
.SH DESCRIPTION
Revoke every persistent grant for NAME.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
<\fINAME\fR>

