.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-login-status 1  "dalgona-login-status " 
.SH NAME
dalgona\-login\-status \- Show provider sign\-in state.
.SH SYNOPSIS
\fBdalgona login status\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Show provider sign\-in state.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
