.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-__sandbox 1  "dalgona-__sandbox " 
.SH NAME
dalgona\-__sandbox \- Enable the configured sandbox.
.SH SYNOPSIS
\fBdalgona\-__sandbox\fR [\fB\-h\fR|\fB\-\-help\fR] 
.SH DESCRIPTION
Enable the configured sandbox.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
