.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH dalgona-logout 1  "dalgona-logout " 
.SH NAME
dalgona\-logout \- Sign out from a provider.
.SH SYNOPSIS
\fBdalgona logout\fR [\fB\-h\fR|\fB\-\-help\fR] [\fIPROVIDER\fR] 
.SH DESCRIPTION
Sign out from a provider.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
[\fIPROVIDER\fR]

